name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Lint
      run: |
        tox -e lint
    - name: Bandit
      run: |
        tox -e bandit
    - name: Install semgrep binary and run tests
      run: |
        wget https://github.com/returntocorp/semgrep/releases/download/v0.5.0-dev.2/semgrep-v0.5.0-dev.2-ubuntu-16.04.tgz
        tar -xvzf semgrep-v0.5.0-dev.2-ubuntu-16.04.tgz
        export PATH="$(pwd)/semgrep-files/:$PATH"
        tox -e py38
    - name: Clean Up
      run: |
        tox -e clean
